exports.FRIEND_ACCEPTED = 'ACCEPTED';
exports.FRIEND_PENDING = 'PENDING';

exports.FRIEND_STATUS_ANNONYMOUS = 'FRIEND_STATUS_ANNONYMOUS';
exports.FRIEND_STATUS_ME = 'FRIEND_STATUS_ME';
exports.FRIEND_STATUS_FRIEND = 'FRIEND_STATUS_FRIEND';
exports.FRIEND_STATUS_REQUESTER = 'FRIEND_STATUS_REQUESTER';
exports.FRIEND_STATUS_ACCEPTER = 'FRIEND_STATUS_ACCEPTER';
